name       : python-tensorboard
version    : 2.1.0
release    : 4
source     :
    - https://github.com/tensorflow/tensorboard/archive/2.1.0.tar.gz : 84a61d5b06c7f41402133b57b3e8bcb2d233911b26a837c4b873fdbf3b1abc4b
license    : Apache-2.0
component  : programming.python
summary    : TensorFlow's Visualization Toolkit
description: |
    TensorBoard is a suite of web applications for inspecting
    and understanding your TensorFlow runs and graphs.
networking : yes
builddeps  :
    - bazel
rundeps    :
    - numpy
    - python-bleach
    - python-grpcio
    - python-markdown
    - python-google-auth-oauthlib
    - python-protobuf
    - python-tensorflow-serving-api
    - python-wheel
    - python-werkzeug
setup      : |
    %patch -p1 < $pkgfiles/bump_tensorflow_version.patch

    bazel build //tensorboard/pip_package:build_pip_package
    RUNFILES=bazel-bin/tensorboard/pip_package/build_pip_package.runfiles/org_tensorflow_tensorboard
    mkdir -p $PKG_BUILD_DIR/pkg
    cp -LR $RUNFILES/tensorboard $PKG_BUILD_DIR/pkg
    pushd $PKG_BUILD_DIR/pkg
    mv -f tensorboard/pip_package/setup.py .
    mv -f tensorboard/pip_package/setup.cfg .
    mv -f tensorboard/pip_package/MANIFEST.in .
    mv -f tensorboard/pip_package/LICENSE .
    mv -f tensorboard/pip_package/README.rst .
    rm -rf tensorboard/pip_package
    rm -f tensorboard/tensorboard
    chmod -x LICENSE
    popd

    bazel shutdown
build      : |
    pushd $PKG_BUILD_DIR/pkg
    python3 setup.py build
    popd
install    : |
    pushd $PKG_BUILD_DIR/pkg
    python3 setup.py install --root="%installroot%"
    popd
