name       : python-tensorboard
version    : 2.10.1
release    : 12
source     :
    - https://files.pythonhosted.org/packages/80/49/a5ec29886ef823718c8ae54ed0b3ad7e19066b5bf21cec5038427e6a04c4/tensorboard-2.10.1-py3-none-any.whl : fb9222c1750e2fa35ef170d998a1e229f626eeced3004494a8849c88c15d8c1c
license    : Apache-2.0
component  : programming.python
summary    : TensorFlow's Visualization Toolkit
description: |
    TensorBoard is a suite of web applications for inspecting
    and understanding your TensorFlow runs and graphs.
rundeps    :
    - numpy
    - python-absl-py
    - python-bleach
    - python-grpcio
    - python-markdown
    - python-google-auth-oauthlib
    - python-protobuf
    - python-tensorflow-serving-api
    - python-wheel
    - python-werkzeug
install    : |
    python3 -m pip install --root=%installroot% --no-deps --disable-pip-version-check --verbose --ignore-installed --no-warn-script-location --no-index --no-cache-dir $sources/*.whl
    rm -fr $installdir/usr/lib/python%python3_version%/site-packages/tensorboard/_vendor/
