name       : python-tensorboard
version    : 2.6.0
release    : 6
source     :
    - https://github.com/tensorflow/tensorboard/archive/refs/tags/2.6.0.tar.gz : 3d1e0a05828b25c1c28bd90c73d981a0a65c6a5550510bc7983d03ab915e6503
license    : Apache-2.0
component  : programming.python
summary    : TensorFlow's Visualization Toolkit
description: |
    TensorBoard is a suite of web applications for inspecting
    and understanding your TensorFlow runs and graphs.
networking : yes
builddeps  :
    - bazel
    - numpy
    - python2-numpy
    - python-absl-py
    - python-attrs
    - python-bleach
    - python-grpcio
    - python-jsonschema
    - python-markdown
    - python-google-auth-oauthlib
    - python-protobuf
    - python-pyrsistent
    - python-tensorflow-serving-api
    - python-wheel
    - python-werkzeug
rundeps    :
    - numpy
    - python-bleach
    - python-grpcio
    - python-markdown
    - python-google-auth-oauthlib
    - python-protobuf
    - python-tensorflow-serving-api
    - python-wheel
    - python-werkzeug
setup      : |
    #patch -p1 < $pkgfiles/bump_tensorflow_version.patch

    bazel build //tensorboard/pip_package:build_pip_package
    RUNFILES=bazel-bin/tensorboard/pip_package/build_pip_package.runfiles/org_tensorflow_tensorboard
    mkdir -p $PKG_BUILD_DIR/pkg
    cp -LR $RUNFILES/tensorboard $PKG_BUILD_DIR/pkg
    pushd $PKG_BUILD_DIR/pkg
    mv -f tensorboard/pip_package/{README.rst,MANIFEST.in,setup.py,setup.cfg,requirements.txt} .
    rm -rf tensorboard/pip_package
    rm -f tensorboard/tensorboard
    popd

    bazel shutdown
build      : |
    pushd $PKG_BUILD_DIR/pkg
    python3 setup.py build
    popd
install    : |
    pushd $PKG_BUILD_DIR/pkg
    python3 setup.py install --root="%installroot%"
    popd
